version: '2'
services:
    workstarter-app:
        image: workstarter
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://workstarter-mysql:3306/workstarter?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=workstarter-elasticsearch:9300
        ports:
            - 8080:8080
    workstarter-mysql:
        extends:
            file: mysql.yml
            service: workstarter-mysql
    workstarter-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: workstarter-elasticsearch
